#!/bin/bash

# Requiert les paquet Debian xsltproc et wkhtmltopdf

xsltproc -o ressources/livret.html ressources/livret.xsl ressources/liste_projets.xml
wkhtmltopdf ressources/livret.html ../Livret.pdf
